#!/bin/bash

VENV_DIR="$HOME/.venv"
VENV_URL="https://raw.github.com/pypa/virtualenv/develop/virtualenv.py"

VENV_CMD="virtualenv"
PIP_COMMANDS="help bundle freeze install search uninstall unzip zip"

is_pip_cmd() {
  for word in $PIP_COMMANDS; do
      [[ $word = $1 ]] && return 0
  done
  return 1
}

ensure_venv() {
	command -v $VENV_CMD 2>/dev/null && return 0

	wget -O $VENV_DIR/virtualenv.py $VENV_URL \
	|| curl -O $VENV_DIR/virtualenv.py $VENV_URL \
	|| exit 1

	chmod 500 $VENV_DIR/virtualenv.py
	VENV_CMD="$VENV_DIR/virtualenv.py"
}

setup() {
	test -x "$VENV_DIR/env/bin/python" && return 0
	test -d "$VENV_DIR" || mkdir -p "$VENV_DIR"
	ensure_venv
	$VENV_CMD $VENV_DIR/env
}

setup

if [ $# -eq 0 ]; then
	exec $VENV_DIR/env/bin/python
elif [ $1 = "help" ]; then
	echo "USAGE:"
	echo "  venv          Start a python shell"
	echo "  venv SCRIPT   Run a script installed to the venv"
	echo "  venv COMMAND  Run a pip command (e.g. install, search, ...)"
	echo "  venv MODULE   Run a python module as a script"
elif [ -x $VENV_DIR/env/bin/$1 ]; then
	CMD=$1
	shift 1
	exec $VENV_DIR/env/bin/$CMD "$@"
elif is_pip_cmd $1; then
	exec $VENV_DIR/env/bin/pip "$@"
else
	MOD=$1
	shift 1
	exec $VENV_DIR/env/bin/python -m$MOD "$@"
fi;
